# Generated by Django 3.0.5 on 2021-03-18 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('experience', models.CharField(max_length=5)),
                ('designation', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('is_java', models.BooleanField(default=False)),
                ('is_html', models.BooleanField(default=False)),
                ('is_css', models.BooleanField(default=False)),
                ('is_js', models.BooleanField(default=False)),
                ('is_python', models.BooleanField(default=False)),
                ('is_angular', models.BooleanField(default=False)),
                ('is_csharp', models.BooleanField(default=False)),
                ('is_react', models.BooleanField(default=False)),
                ('is_php', models.BooleanField(default=False)),
                ('is_cplus', models.BooleanField(default=False)),
                ('is_ml', models.BooleanField(default=False)),
                ('is_mysql', models.BooleanField(default=False)),
                ('is_nosql', models.BooleanField(default=False)),
                ('is_bootstrap', models.BooleanField(default=False)),
                ('is_ruby', models.BooleanField(default=False)),
                ('is_nodejs', models.BooleanField(default=False)),
                ('is_oracle', models.BooleanField(default=False)),
                ('is_creativity', models.BooleanField(default=False)),
                ('is_leadership', models.BooleanField(default=False)),
                ('is_communication', models.BooleanField(default=False)),
                ('is_passion', models.BooleanField(default=False)),
                ('is_teamwork', models.BooleanField(default=False)),
                ('is_analytical', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('contactno', models.CharField(max_length=5)),
                ('solution_description', models.CharField(max_length=40)),
                ('date_admitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField()),
                ('is_java', models.BooleanField(default=False)),
                ('is_html', models.BooleanField(default=False)),
                ('is_css', models.BooleanField(default=False)),
                ('is_js', models.BooleanField(default=False)),
                ('is_python', models.BooleanField(default=False)),
                ('is_angular', models.BooleanField(default=False)),
                ('is_csharp', models.BooleanField(default=False)),
                ('is_react', models.BooleanField(default=False)),
                ('is_php', models.BooleanField(default=False)),
                ('is_cplus', models.BooleanField(default=False)),
                ('is_ml', models.BooleanField(default=False)),
                ('is_mysql', models.BooleanField(default=False)),
                ('is_nosql', models.BooleanField(default=False)),
                ('is_bootstrap', models.BooleanField(default=False)),
                ('is_ruby', models.BooleanField(default=False)),
                ('is_nodejs', models.BooleanField(default=False)),
                ('is_oracle', models.BooleanField(default=False)),
                ('is_creativity', models.BooleanField(default=False)),
                ('is_leadership', models.BooleanField(default=False)),
                ('is_communication', models.BooleanField(default=False)),
                ('is_passion', models.BooleanField(default=False)),
                ('is_teamwork', models.BooleanField(default=False)),
                ('is_analytical', models.BooleanField(default=False)),
                ('repolink', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
